configurations = [
  {
    'id': '11',
    'format_prompt': lambda formatted_context, question: f"Contexto:\n{formatted_context}\n\nPregunta:\n{question}\n\nPor favor, proporcione una respuesta concisa: ",
    'chunk_size': 1500,
    'chunk_overlap': 100,
    'vector_store': 'chroma',
    'embedding_model': 'nomic-embed-text',
  },
    {
    'id': '12',
    'format_prompt': lambda formatted_context, question: f"Contexto:\n{formatted_context}\n\nPregunta:\n{question}\n\nPor favor, proporcione una respuesta concisa: ",
    'chunk_size': 500,
    'chunk_overlap': 100,
    'vector_store': 'chroma',
    'embedding_model': 'llama3',
  },
  {
    'id': '13',
    'format_prompt': lambda formatted_context, question: f"Contexto:\n{formatted_context}\n\nPregunta:\n{question}\n\nPor favor, proporcione una respuesta concisa: ",
    'chunk_size': 1000,
    'chunk_overlap': 100,
    'vector_store': 'chroma',
    'embedding_model': 'llama3',
  },
  {
    'id': '14',
    'format_prompt': lambda formatted_context, question: f"Contexto:\n{formatted_context}\n\nPregunta:\n{question}\n\nPor favor, proporcione una respuesta concisa: ",
    'chunk_size': 1500,
    'chunk_overlap': 100,
    'vector_store': 'chroma',
    'embedding_model': 'llama3',
  },

    {
    'id': '15',
    'format_prompt': lambda formatted_context, question: f"Contexto:\n{formatted_context}\n\nPregunta:\n{question}\n\nPor favor, proporcione una respuesta concisa: ",
    'chunk_size': 500,
    'chunk_overlap': 100,
    'vector_store': 'chroma',
    'embedding_model': 'mxbai-embed-large',
  },
  {
    'id': '16',
    'format_prompt': lambda formatted_context, question: f"Contexto:\n{formatted_context}\n\nPregunta:\n{question}\n\nPor favor, proporcione una respuesta concisa: ",
    'chunk_size': 1000,
    'chunk_overlap': 100,
    'vector_store': 'chroma',
    'embedding_model': 'mxbai-embed-large',
  },
  {
    'id': '17',
    'format_prompt': lambda formatted_context, question: f"Contexto:\n{formatted_context}\n\nPregunta:\n{question}\n\nPor favor, proporcione una respuesta concisa: ",
    'chunk_size': 1500,
    'chunk_overlap': 100,
    'vector_store': 'chroma',
    'embedding_model': 'mxbai-embed-large',
  },
  {
    'id': '0',
    'format_prompt': lambda formatted_context, question: f"Contexto:\n{formatted_context}\n\nPregunta:\n{question}\n\nPor favor, proporcione una respuesta concisa: ",
    'chunk_size': 500,
    'chunk_overlap': 100,
    'vector_store': 'faiss',
    'embedding_model': 'nomic-embed-text',
  },
  {
    'id': '1',
    'format_prompt': lambda formatted_context, question: f"Contexto:\n{formatted_context}\n\nPregunta:\n{question}\n\nPor favor, proporcione una respuesta concisa: ",
    'chunk_size': 1000,
    'chunk_overlap': 100,
    'vector_store': 'faiss',
    'embedding_model': 'nomic-embed-text',
  },
  {
    'id': '2',
    'format_prompt': lambda formatted_context, question: f"Contexto:\n{formatted_context}\n\nPregunta:\n{question}\n\nPor favor, proporcione una respuesta concisa: ",
    'chunk_size': 1500,
    'chunk_overlap': 100,
    'vector_store': 'faiss',
    'embedding_model': 'nomic-embed-text',
  },
    {
    'id': '3',
    'format_prompt': lambda formatted_context, question: f"Contexto:\n{formatted_context}\n\nPregunta:\n{question}\n\nPor favor, proporcione una respuesta concisa: ",
    'chunk_size': 500,
    'chunk_overlap': 100,
    'vector_store': 'faiss',
    'embedding_model': 'llama3',
  },
  {
    'id': '4',
    'format_prompt': lambda formatted_context, question: f"Contexto:\n{formatted_context}\n\nPregunta:\n{question}\n\nPor favor, proporcione una respuesta concisa: ",
    'chunk_size': 1000,
    'chunk_overlap': 100,
    'vector_store': 'faiss',
    'embedding_model': 'llama3',
  },
  {
    'id': '5',
    'format_prompt': lambda formatted_context, question: f"Contexto:\n{formatted_context}\n\nPregunta:\n{question}\n\nPor favor, proporcione una respuesta concisa: ",
    'chunk_size': 1500,
    'chunk_overlap': 100,
    'vector_store': 'faiss',
    'embedding_model': 'llama3',
  },

    {
    'id': '6',
    'format_prompt': lambda formatted_context, question: f"Contexto:\n{formatted_context}\n\nPregunta:\n{question}\n\nPor favor, proporcione una respuesta concisa: ",
    'chunk_size': 500,
    'chunk_overlap': 100,
    'vector_store': 'faiss',
    'embedding_model': 'mxbai-embed-large',
  },
  {
    'id': '7',
    'format_prompt': lambda formatted_context, question: f"Contexto:\n{formatted_context}\n\nPregunta:\n{question}\n\nPor favor, proporcione una respuesta concisa: ",
    'chunk_size': 1000,
    'chunk_overlap': 100,
    'vector_store': 'faiss',
    'embedding_model': 'mxbai-embed-large',
  },
  {
    'id': '8',
    'format_prompt': lambda formatted_context, question: f"Contexto:\n{formatted_context}\n\nPregunta:\n{question}\n\nPor favor, proporcione una respuesta concisa: ",
    'chunk_size': 1500,
    'chunk_overlap': 100,
    'vector_store': 'faiss',
    'embedding_model': 'mxbai-embed-large',
  },
  {
    'id': '9',
    'format_prompt': lambda formatted_context, question: f"Contexto:\n{formatted_context}\n\nPregunta:\n{question}\n\nPor favor, proporcione una respuesta concisa: ",
    'chunk_size': 500,
    'chunk_overlap': 100,
    'vector_store': 'chroma',
    'embedding_model': 'nomic-embed-text',
  },
  {
    'id': '10',
    'format_prompt': lambda formatted_context, question: f"Contexto:\n{formatted_context}\n\nPregunta:\n{question}\n\nPor favor, proporcione una respuesta concisa: ",
    'chunk_size': 1000,
    'chunk_overlap': 100,
    'vector_store': 'chroma',
    'embedding_model': 'nomic-embed-text',
  },
]